// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/search-properties.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.53.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-properties.ts
var search_properties_default = defineTool({
  name: "search_properties",
  title: "Search property listings",
  description: "Search active NYC-area real estate listings (Queens, Manhattan, Brooklyn, Bronx, Staten Island, Nassau County) by city, price range, bedrooms, and property type.",
  inputSchema: {
    city: z.string().trim().optional().describe("City name filter, e.g. 'Flushing'."),
    state: z.string().trim().optional().describe("Two-letter state code, e.g. 'NY'."),
    min_price: z.number().int().nonnegative().optional().describe("Minimum price in USD."),
    max_price: z.number().int().nonnegative().optional().describe("Maximum price in USD."),
    min_bedrooms: z.number().int().nonnegative().optional().describe("Minimum bedroom count."),
    property_type: z.string().trim().optional().describe("Property type filter, e.g. 'condo'."),
    limit: z.number().int().min(1).max(50).default(10).describe("Maximum results to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city, state, min_price, max_price, min_bedrooms, property_type, limit }) => {
    const supabase = supabaseAnon();
    let query = supabase.from("properties").select(
      "id,title,price,address,city,state,zip_code,bedrooms,bathrooms,square_feet,property_type,price_per_sqft,market_score,value_score,listing_url"
    ).eq("is_active", true).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (city) query = query.ilike("city", `%${city}%`);
    if (state) query = query.ilike("state", state);
    if (typeof min_price === "number") query = query.gte("price", min_price);
    if (typeof max_price === "number") query = query.lte("price", max_price);
    if (typeof min_bedrooms === "number") query = query.gte("bedrooms", min_bedrooms);
    if (property_type) query = query.ilike("property_type", `%${property_type}%`);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: data && data.length ? JSON.stringify(data, null, 2) : "No matching active listings found."
        }
      ],
      structuredContent: { count: data?.length ?? 0, properties: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-property.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_property_default = defineTool2({
  name: "get_property",
  title: "Get property details",
  description: "Fetch the full details of one property listing by its id.",
  inputSchema: {
    id: z2.string().uuid().describe("The property id returned by search_properties.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("properties").select("*").eq("id", id).eq("is_active", true).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: `No active listing found for id ${id}.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { property: data }
    };
  }
});

// src/lib/mcp/tools/estimate-roi.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^3.25.76";
var estimate_roi_default = defineTool3({
  name: "estimate_roi",
  title: "Estimate investment ROI",
  description: "Estimate cap rate, monthly cash flow, and cash-on-cash return for a rental property investment.",
  inputSchema: {
    purchase_price: z3.number().positive().describe("Purchase price in USD."),
    down_payment_percent: z3.number().min(0).max(100).default(20).describe("Down payment as a percentage of price."),
    interest_rate_percent: z3.number().min(0).max(30).default(6.5).describe("Annual mortgage rate."),
    loan_years: z3.number().int().min(1).max(40).default(30).describe("Mortgage term in years."),
    monthly_rent: z3.number().nonnegative().describe("Expected gross monthly rent in USD."),
    monthly_expenses: z3.number().nonnegative().default(0).describe("Monthly taxes, insurance, HOA, maintenance, and management in USD."),
    vacancy_percent: z3.number().min(0).max(50).default(5).describe("Assumed vacancy rate.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({
    purchase_price,
    down_payment_percent,
    interest_rate_percent,
    loan_years,
    monthly_rent,
    monthly_expenses,
    vacancy_percent
  }) => {
    const down = purchase_price * ((down_payment_percent ?? 20) / 100);
    const loan = purchase_price - down;
    const r = (interest_rate_percent ?? 6.5) / 100 / 12;
    const n = (loan_years ?? 30) * 12;
    const mortgage = r === 0 ? loan / n : loan * r * Math.pow(1 + r, n) / (Math.pow(1 + r, n) - 1);
    const effectiveRent = monthly_rent * (1 - (vacancy_percent ?? 5) / 100);
    const expenses = monthly_expenses ?? 0;
    const noiMonthly = effectiveRent - expenses;
    const capRate = noiMonthly * 12 / purchase_price;
    const cashFlow = noiMonthly - mortgage;
    const cashOnCash = down > 0 ? cashFlow * 12 / down : 0;
    const round = (v) => Math.round(v * 100) / 100;
    const result = {
      down_payment: round(down),
      loan_amount: round(loan),
      monthly_mortgage_payment: round(mortgage),
      effective_monthly_rent: round(effectiveRent),
      monthly_noi: round(noiMonthly),
      monthly_cash_flow: round(cashFlow),
      annual_cash_flow: round(cashFlow * 12),
      cap_rate_percent: round(capRate * 100),
      cash_on_cash_return_percent: round(cashOnCash * 100)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/get-agent-contact.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
var get_agent_contact_default = defineTool4({
  name: "get_agent_contact",
  title: "Get agent contact info",
  description: "Return the public contact details and service areas for Henry Yue, the NYC real estate investment agent behind this site.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Henry Yue",
      chinese_name: "\u5CB3\u5148\u751F",
      title: "NYC Real Estate Investment Expert",
      phone: "+1 (718) 717-5210",
      email: "RealHenryYue@gmail.com",
      website: "https://www.realhenryyue.com",
      languages: ["English", "Chinese (Mandarin)"],
      service_areas: [
        "Manhattan",
        "Queens",
        "Brooklyn",
        "Bronx",
        "Staten Island",
        "Nassau County"
      ],
      services: [
        "AI-assisted investment analysis",
        "ROI and cash-flow modeling",
        "Residential sales and purchases",
        "Market and neighborhood research"
      ]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "queens-long-island-realestate",
  title: "queens-long-island-realestate",
  version: "0.1.0",
  instructions: "Public tools for Henry Yue's NYC real estate investment site. Use `search_properties` to find active listings by city, price, or bedrooms, `get_property` for full details of one listing, `estimate_roi` to model cap rate and cash flow for an investment, and `get_agent_contact` for the agent's public contact details and service areas.",
  tools: [search_properties_default, get_property_default, estimate_roi_default, get_agent_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
