// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddfafaeypfnnxbkbgokr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkZmFmYWV5cGZubnhia2Jnb2tyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODQ1MTksImV4cCI6MjA2OTU2MDUxOX0.KL8vD42DfgaZEb0_dJmjNNUqSSEwVdzeevcOZwVit9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});